---
- name: Install nginx with Virtual Hosts
  hosts: webservers
  remote_user: victor
  become: true
  become_method: sudo
  gather_facts: no

  vars:
    sites:
    - "etis.com"
    - "fizfak.com"
    - "mehmat.ru"

  roles:
  - nginx-vhosts

